In [2]:
import pandas as pd
import numpy as np
import json, os

In [3]:
dirPath = input("Directory of Data files: ")
listDir = [dirPath+"\\"+dp for dp in os.listdir(dirPath) if ".txt" in dp] # C:\Users\USER\Documents\GitHub\cofico\cofico\FROM BIM MASTER TEMP 210412\Python\pyAutocad\CAD DATA

Directory of Data files:  C:\Users\USER\Documents\GitHub\cofico\cofico\FROM BIM MASTER TEMP 210412\Python\pyAutocad\CAD DATA

### 1. READ TXT + MERGE/CONCENTRATE DATAFRAME

In [7]:
# for dp in listDir:
# dp = listDir[0]
data = pd.concat([pd.read_csv(dp, delimiter = "\t") for dp in listDir])
# data.info()
data.head()

,Count,Name,Author,Color,Comments,Drawing Revision Number,EdgeStyleId,FaceStyleId,File Accessed,File Created,...,Position Z,Rotation,Style,Subject,Thickness,Title,Total Editing Time,Value,VisualStyleId,Width Factor
0,1,Text,NaN,green,NaN,NaN,(0),(0),15/05/2021 6:11:20 PM,15/05/2021 4:24:14 PM,...,0.0,0.0,TTP-HelCon,NaN,0.0,NaN,28610,VC-1.12,(0),1.0
1,1,Text,NaN,green,NaN,NaN,(0),(0),15/05/2021 6:11:20 PM,15/05/2021 4:24:14 PM,...,0.0,0.0,TTP-HelCon,NaN,0.0,NaN,28610,VC-1.13,(0),1.0
2,1,Text,NaN,green,NaN,NaN,(0),(0),15/05/2021 6:11:20 PM,15/05/2021 4:24:14 PM,...,0.0,0.0,TTP-HelCon,NaN,0.0,NaN,28610,VC-6.6,(0),1.0
3,1,Text,NaN,green,NaN,NaN,(0),(0),15/05/2021 6:11:20 PM,15/05/2021 4:24:14 PM,...,0.0,0.0,TTP-HelCon,NaN,0.0,NaN,28610,VC-6.7,(0),1.0
4,1,Text,NaN,green,NaN,NaN,(0),(0),15/05/2021 6:11:20 PM,15/05/2021 4:24:14 PM,...,0.0,0.0,TTP-HelCon,NaN,0.0,NaN,28610,VC-1.14,(0),1.0

### 2. SELECT COLUMN BECOME INDEX COLUMN

In [12]:
columnName = input(" Column Name for New Data **Index**:")

 Column Name for New Data **Index**: Value

### 3. SORT BY VALUE + REMOVE DUPLICATE

In [13]:
# indexColumn = data[columnName]
data.sort_values(by=columnName,inplace = True,ascending = True)
data.dropna(subset=[columnName], inplace = True)
count1 = data.shape[0]
data.drop_duplicates(subset = [columnName],inplace = True)
count2 = data.shape[0]
print("REVOVED ",count1-count2," DUPLICATE at ***",columnName,"*** COLUMN")

data

REVOVED  0  DUPLICATE at *** Value *** COLUMN

,Count,Name,Author,Color,Comments,Drawing Revision Number,EdgeStyleId,FaceStyleId,File Accessed,File Created,...,Position Z,Rotation,Style,Subject,Thickness,Title,Total Editing Time,Value,VisualStyleId,Width Factor
493,1,Text,NaN,ByLayer,NaN,NaN,(0),(0),17/5/2021 10:47:21 am,17/5/2021 10:47:21 am,...,0.0,0.0,$0$TTP-HelCon,NaN,0.0,NaN,11582485,-3.450,(0),1.00
173,1,Text,NaN,ByLayer,NaN,NaN,(0),(0),17/5/2021 10:47:21 am,17/5/2021 10:47:21 am,...,0.0,0.0,$0$CHG_XX_Damsan_Ham 2$0$TTP-HelCon,NaN,0.0,NaN,3872411,-6.750,(0),1.00
154,1,Text,NaN,ByLayer,NaN,NaN,(0),(0),17/5/2021 10:47:21 am,17/5/2021 10:47:21 am,...,0.0,0.0,$1$CHG_XX_Damsan_Ham 2$0$TTP-HelCon,NaN,0.0,NaN,3872411,-6.780,(0),1.00
332,1,Text,NaN,ByLayer,NaN,NaN,(0),(0),17/5/2021 10:47:21 am,17/5/2021 10:47:21 am,...,0.0,0.0,$0$CHG_XX_Damsan_Ham 2$0$TTP-HelCon,NaN,0.0,NaN,3872411,-7.600,(0),1.00
125,1,Text,NaN,ByLayer,NaN,NaN,(0),(0),17/5/2021 10:47:21 am,17/5/2021 10:47:21 am,...,0.0,0.0,$0$CHG_XX_Damsan_Ham 2$0$TTP-HelCon,NaN,0.0,NaN,3872411,-8.750,(0),1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,1,Text,NaN,ByLayer,NaN,NaN,(0),(0),17/5/2021 10:47:21 am,17/5/2021 10:47:21 am,...,0.0,0.0,$0$CHG_XX_Damsan_Ham 2$0$TTP-HelCon,NaN,0.0,NaN,3872411,e = 650,(0),1.00
302,1,Text,NaN,ByLayer,NaN,NaN,(0),(0),17/5/2021 10:47:22 am,17/5/2021 10:47:22 am,...,0.0,0.0,TTP-HelCon,NaN,0.0,NaN,3891549,theo RFI,(0),0.85
118,1,Text,NaN,ByLayer,NaN,NaN,(0),(0),17/5/2021 2:15:51 pm,17/5/2021 2:15:51 pm,...,"0'-0""",0.0,Arial - Bold,NaN,"0'-0""",NaN,13939,ĐOÀN VĂN HUY,(0),1.00
114,1,Text,NaN,ByLayer,NaN,NaN,(0),(0),17/5/2021 2:15:51 pm,17/5/2021 2:15:51 pm,...,"0'-0""",0.0,A1 BORDER$0$Title Block DD$0$ARIAL,NaN,"0'-0""",NaN,13939,ĐẠI DIỆN CHỦ ĐẦU TƯ - ON BEHALF OF CLIENT,(0),1.00
119,1,Text,NaN,ByLayer,NaN,NaN,(0),(0),17/5/2021 2:15:51 pm,17/5/2021 2:15:51 pm,...,"0'-0""",0.0,Arial - Bold,NaN,"0'-0""",NaN,13939,ĐẶNG NGỌC PHƯƠNG,(0),1.00

### 4. FILTER DATA - by START WITH

In [14]:
filterValues = input("Fitered Values :")

listFilterValues = filterValues.split()
listFilterValues

Fitered Values : VH CH DH

['VH', 'CH', 'DH']

In [15]:
for sw in listFilterValues:
    print (data[columnName].str.match(sw))

493    False
173    False
154    False
332    False
125    False
       ...
126    False
302    False
118    False
114    False
119    False
Name: Value, Length: 1278, dtype: bool
493    False
173    False
154    False
332    False
125    False
       ...
126    False
302    False
118    False
114    False
119    False
Name: Value, Length: 1278, dtype: bool
493    False
173    False
154    False
332    False
125    False
       ...
126    False
302    False
118    False
114    False
119    False
Name: Value, Length: 1278, dtype: bool

### 5. CREATE NEW DATAFRAME

### 6.PLOT + EXPORT EXTERNAL DATA

In [7]:
# data.plot(kind = 'scatter', x = 'Position X', y = 'Position Y')

### 7. FIND NEAREST DATA TO REVIT MODEL ELEMENT DATA

###

In [17]:
pd.Series(["1", "2", "3a", "3b", "03c", "4dx"],dtype="string")

0      1
1      2
2     3a
3     3b
4    03c
5    4dx
dtype: string